Algoritmo "aula8ex39"
// Disciplina   : [Algoritmos e Lógica de Programação]
// Professor   :Ely 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Alexandre
// Data atual  : 10/7/2020
Var
// Seção de Declarações das variáveis 
a, b, c :inteiro
i : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a<-0
b<-1
c<-0
escreval(a)
escreval(b)
para i de 1 ate 18 faca
c<-a + b
escreval(c)
a<-b
b<-C
fimpara

Fimalgoritmo